@startuml
Sender -> Sender: Analyse Files(Fetch Data)
Sender -> Sender: Split Files
Sender -> Sender: Create PCB File
Sender -> Sender: Create Index File
Sender -> Sender: Create ZIP File
Sender -> Sender: Encrypt With DES_CBC
Sender -> FTPServer: Upload ZIP File
Sender -> Sender: Delete local ZIP file

Receiver <-> FTPServer: Download ZIP File
Receiver -> Receiver: Decrypt With DES_CBC
Receiver -> Receiver: Unzip ZIP File
Receiver -> Receiver: Resolving Index File
Receiver -> Receiver: Import data to database
Receiver -> FTPServer: Delete ZIP file
@enduml