@startuml
participant Sender
participant FGAP
participant Receiver
actor Worker

alt upload case
    Sender -> Sender: Fetch Data
    Sender -> Sender: Split Data
    Sender -> Sender: Create PCB File
    Sender -> Sender: Create Index File
    Sender -> Sender: Create ZIP File
    Sender -> Sender: Encrypt With DES_CBC
    Sender -> FGAP: Upload ZIP File
    Sender -> Sender: Write record to db
    Sender -> Sender: Delete local overdue ZIP file(Schedule)
end
alt download case
    Receiver <-> FGAP: Download ZIP File
    Receiver -> Receiver: Decrypt With DES_CBC
    Receiver -> Receiver: Unzip ZIP File
    Receiver -> Receiver: Resolving Index File
    Receiver -> Receiver: Import data to database(bak?) ?
    Receiver -> FGAP: Delete ZIP file
else some kind of failure
    Receiver -> Worker: notify
    Worker -> Sender: notify
    Sender -> FGAP: Retry upload zip file
end
@enduml