
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xender?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  type-aliases-package: org.warless.xender.entity
  mapper-locations: classpath:mapper/*.xml

xender:
  ftp:
    host: 192.168.1.102
    port: 21
    username: Anonymous
    password:
    file-type: 2
    use-protocol: false

logging:
  path: logs/

# @Value("${xender.ftp.host:127.0.0.1}")
# private String host;
# @Value("${xender.ftp.port:21}")
# private int port;
# @Value("${xender.ftp.username:Anonymous}")
# private String username;
# @Value("${xender.ftp.password:}")
# private String password;